import re
import subprocess
import sys
from pathlib import Path


_REQUIRED_SECTIONS = ["Profile", "Experience", "Education", "Skills"]
_PLACEHOLDERS = [
    "SUMMARY", "EXPERIENCE", "EDUCATION", "SKILLS",
    "PROJECTS", "CERTIFICATIONS", "AWARDS", "VOLUNTEER",
    "LANGUAGES", "SECTION_PROFILE", "SECTION_EXPERIENCE",
    "SECTION_EDUCATION", "SECTION_SKILLS", "SECTION_PROJECTS",
    "SECTION_CERTIFICATIONS", "SECTION_AWARDS", "SECTION_VOLUNTEER",
    "SECTION_LANGUAGES",
]


class CheckResult:
    ok: int = 0
    warn: int = 0
    fail: int = 0

    def ok_(self, msg: str) -> None:
        self.ok += 1
        _print("[OK]", msg)

    def warn_(self, msg: str) -> None:
        self.warn += 1
        _print("[WARN]", msg)

    def fail_(self, msg: str) -> None:
        self.fail += 1
        _print("[FAIL]", msg)


def _print(tag: str, msg: str) -> None:
    print(f"{tag} {msg}")


def _run(cmd: list[str], cwd: str | None = None) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, capture_output=True, text=True, cwd=cwd)


def _text_has_control_chars(text: str) -> bool:
    for ch in text:
        cp = ord(ch)
        if cp < 32 and cp not in (9, 10, 12, 13) and cp not in range(0x14, 0x1E):
            return True
        if 0x7F <= cp <= 0x9F:
            return True
        if cp == 0xFFFD:
            return True
    return False


def _read_metadata(pdf_path: Path) -> dict[str, str]:
    r = _run(["exiftool", str(pdf_path)])
    if r.returncode != 0:
        return {}
    meta: dict[str, str] = {}
    for line in r.stdout.splitlines():
        if ":" not in line:
            continue
        key, _, val = line.partition(":")
        key = key.strip()
        val = val.strip()
        meta[key] = val
    return meta


def _parse_keywords(val: str) -> list[str]:
    return [kw.strip() for kw in val.split(",") if kw.strip()]


def check_pdf(pdf_path: Path) -> int:
    result = CheckResult()

    print(f"ATS compatibility check: {pdf_path}\n")

    if not pdf_path.exists():
        result.fail_("File not found")
        _print("", f"\nResult: FAIL ({result.fail} failure(s))")
        return 1

    # --- 0. Metadata ---
    meta = _read_metadata(pdf_path)

    author = meta.get("Author", "")
    subject = meta.get("Subject", "")
    kw_raw = meta.get("Keywords", "")
    kw_skills = meta.get("X-Keywords-Skills", "")
    kw_experience = meta.get("X-Keywords-Experience", "")
    kw_projects = meta.get("X-Keywords-Projects", "")
    x_app = meta.get("X-App", "")
    x_engine = meta.get("X-Engine", "")

    is_curriculum_gen = x_app == "hirepaper"

    if is_curriculum_gen:
        result.ok_(f"PDF generated by: hirepaper")
    elif x_app:
        result.warn_(f"X-App is '{x_app}', expected 'hirepaper'")
    else:
        result.warn_("X-App metadata not found (PDF may not be from hirepaper)")

    if author:
        result.ok_(f"Candidate: {author}")
    if subject:
        result.ok_(f"Headline: {subject}")

    if x_engine == "lualatex":
        result.ok_(f"Generation engine: {x_engine}")
    elif x_engine:
        result.fail_(f"Generation engine is '{x_engine}', expected 'lualatex'")
    else:
        result.warn_("X-Engine metadata not found")

    # Collect keywords: use X-Keywords-* from exiftool, fallback to standard Keywords
    if kw_skills or kw_experience or kw_projects:
        kw_source_skills = kw_skills
        kw_source_exp = kw_experience
        kw_source_proj = kw_projects
    else:
        kw_source_skills = ""
        kw_source_exp = ""
        kw_source_proj = ""
        kw_aggregated = kw_raw

    if is_curriculum_gen:
        if not kw_raw:
            result.warn_("Keywords metadata missing or empty")
        for label, val in [("Skills", kw_source_skills), ("Experience", kw_source_exp), ("Projects", kw_source_proj)]:
            if not val:
                result.warn_(f"X-Keywords-{label} metadata missing or empty")

        if kw_source_skills and kw_source_exp and kw_source_proj and kw_raw:
            expected = sorted(dict.fromkeys(_parse_keywords(kw_source_skills) + _parse_keywords(kw_source_exp) + _parse_keywords(kw_source_proj)))
            actual = sorted(_parse_keywords(kw_raw))
            if expected == actual:
                result.ok_("Keywords match union of X-Keywords-* fields")
            else:
                result.warn_("Keywords differ from union of X-Keywords-* fields")
    elif not kw_raw:
        result.warn_("Keywords metadata missing or empty")

    if kw_source_skills or kw_source_exp or kw_source_proj:
        combined = _parse_keywords(kw_source_skills) + _parse_keywords(kw_source_exp) + _parse_keywords(kw_source_proj)
        keywords = list(dict.fromkeys(combined))
    elif kw_raw:
        keywords = _parse_keywords(kw_raw)
    else:
        keywords = []

    # --- 1. Text extraction ---
    r = _run(["pdftotext", str(pdf_path), "-"])
    if r.returncode != 0:
        result.fail_("Text extraction failed (pdftotext error)")
        _print("", f"\nResult: FAIL ({result.fail} failure(s))")
        return 1

    text = r.stdout
    if not text.strip():
        result.fail_("Text extraction returned empty output")
        _print("", "  Diagnostic hints:")
        _print("", "  - PDF may be partially generated after a LaTeX failure")
        _print("", "  - Font loading (luaotfload/fontspec) may have failed or cache not writable")
        _print("", "  - Check with: pdffonts <pdf>")
        _print("", "  - Build logs may contain luaotfload or fontspec errors")
        _print("", f"\nResult: FAIL ({result.fail} failure(s))")
        return 1

    result.ok_("Text extraction succeeded")

    # --- 2. Corrupted character detection ---
    if _text_has_control_chars(text):
        result.fail_("Corrupted extraction characters detected (control chars in output)")
    else:
        result.ok_("No corrupted extraction characters detected")

    # --- 3. Font check ---
    r2 = _run(["pdffonts", str(pdf_path)])
    fonts_output = r2.stdout
    if r2.returncode != 0:
        result.warn_("Font inspection could not run (pdffonts error)")
    else:
        has_type3 = False
        has_unicode_info = False
        for line in fonts_output.splitlines()[2:]:
            line = line.strip()
            if not line:
                continue
            if "Type 3" in line:
                has_type3 = True
            if re.search(r'\s+Uni\s+|\s+Identity-H\s+', line):
                has_unicode_info = True

        if has_type3:
            result.fail_("Type 3 fonts found (ATS-unsafe)")
        else:
            result.ok_("No Type 3 fonts found")

        if has_unicode_info:
            result.ok_("Fonts expose Unicode mapping")
        else:
            result.warn_("Some fonts may not expose Unicode mapping")

    # --- 4. Required section check ---
    clean_text = re.sub(r"[\x00-\x08\x0B\x0C\x0E-\x1F\x7F-\x9F]", "", text)
    found_sections = []
    missing_sections = []
    for section in _REQUIRED_SECTIONS:
        low = clean_text.lower()
        pat = section.lower()
        if pat in low:
            found_sections.append(section)
        elif section == "Profile" and "summary" in low:
            found_sections.append("Profile (via Summary alias)")
        elif len(pat) > 3 and pat[:3] in low:
            found_sections.append(f"{section} (approximate)")
        else:
            missing_sections.append(section)

    if missing_sections:
        result.fail_(f"Required sections not found: {', '.join(missing_sections)}")
    else:
        result.ok_(f"Required sections found: {', '.join(found_sections)}")

    # --- 5a. Percentage preservation ---
    pct_matches = re.findall(r'\b\d+(?:\.\d+)?%', clean_text)
    if pct_matches:
        result.ok_(f"Percentages preserved: {', '.join(pct_matches)}")
    else:
        lost = len(re.findall(r'\b\d+(?=[^\S]|$)', clean_text))
        if lost > 0:
            result.warn_("No percentages found in extracted text (possible LaTeX comment loss)")

    # --- 5b. Contact visibility ---
    has_email = bool(re.search(r"[\w.+-]+@[\w-]+\.[\w.-]+", clean_text))
    has_phone = bool(re.search(r"\+?\d[\d\s().-]{7,}\d", clean_text))
    has_location = bool(re.search(r"\b(São Paulo|SP|[A-Z][a-z]+,\s*[A-Z]{2})\b", clean_text))

    contact_checks = []
    if has_email:
        contact_checks.append("email")
    if has_phone:
        contact_checks.append("phone")
    if has_location:
        contact_checks.append("location")

    if contact_checks:
        result.ok_(f"Contact information found: {', '.join(contact_checks)}")
    else:
        result.fail_("No contact information found in extracted text")

    if not has_email:
        result.warn_("No email address detected in extracted text")
    if not has_phone:
        result.warn_("No phone number detected in extracted text")

    # --- 5c. Icon garbage detection near contact lines ---
    contact_lines = [l for l in clean_text.splitlines() if '@' in l or re.search(r'\+?\d{7,}', l)]
    for cl in contact_lines:
        garbage = re.findall(r'[^\x20-\x7E\xA0-\xFF]', cl)
        if garbage:
            unique_garbage = ''.join(set(garbage))
            result.warn_(f"Possible icon garbage characters near contact: {repr(unique_garbage)}")

    # --- 6. Link visibility ---
    generic_link_count = len(re.findall(r"\[link\]|\[credential\]", clean_text))
    url_count = len(re.findall(r"https?://[^\s]+", clean_text))
    clean_url_count = len(re.findall(r'(?:^|(?<=\s))[a-zA-Z0-9][-a-zA-Z0-9.]*\.[a-zA-Z]{2,}(?:/[^\s()<>"]*)?', clean_text))

    if generic_link_count > 0:
        result.fail_(f"Generic hidden link labels found: {generic_link_count} occurrence(s)")
    if url_count > 0 or clean_url_count > 0:
        result.ok_(f"Visible URLs found in extracted text: {url_count + clean_url_count}")
    else:
        result.warn_("No explicit URLs found in extracted text")

    # --- 7. Placeholder check ---
    found_placeholders = [p for p in _PLACEHOLDERS if p in clean_text]
    if found_placeholders:
        result.fail_(f"Template placeholders remain in output: {', '.join(found_placeholders)}")
    else:
        result.ok_("No template placeholders found in extracted text")

    # --- 8. Keyword preservation (from metadata) ---
    if keywords:
        found_keywords = []
        missing_keywords = []
        for kw in keywords:
            escaped = re.escape(kw)
            if re.search(rf"\b{escaped}\b", clean_text) or kw.lower() in clean_text.lower():
                found_keywords.append(kw)
            else:
                missing_keywords.append(kw)

        if found_keywords:
            result.ok_(f"Keywords found: {', '.join(found_keywords)}")
        if missing_keywords:
            result.warn_(f"Keywords not found in extracted text: {', '.join(missing_keywords)}")

    # --- 9. Bullet length / content scanability ---
    long_lines = [l for l in clean_text.splitlines() if len(l.strip()) > 180]
    if long_lines:
        result.warn_(
            f"Unusually long line(s) detected ({len(long_lines)} line(s) > 180 characters) "
            f"--- consider splitting for recruiter scanability"
        )

    # --- Summary ---
    if result.fail > 0:
        _print("", f"\nResult: FAIL ({result.fail} failure(s), {result.warn} warning(s), {result.ok} ok)")
        return 1
    elif result.warn > 0:
        _print("", f"\nResult: PASS with warnings ({result.warn} warning(s), {result.ok} ok)")
        return 0
    else:
        _print("", f"\nResult: PASS ({result.ok} checks passed)")
        return 0
